name: EDFViewerMac
options:
  bundleIdPrefix: com.goldenarc
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: false
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  EDFViewerMac:
    type: application
    platform: macOS
    configFiles:
      Debug: configs/Debug.xcconfig
      Release: configs/Release.xcconfig
    sources:
      - path: Sources/EDFViewerMac
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.goldenarc.edfviewer
        PRODUCT_NAME: EDFViewer
        EXECUTABLE_NAME: EDFViewer
        PRODUCT_MODULE_NAME: EDFViewerMac
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.medical"
        INFOPLIST_KEY_CFBundleDisplayName: "EDF Viewer"
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_DEBUG_DYLIB: NO
        COMBINE_HIDPI_IMAGES: YES
  EDFViewerMacTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/EDFViewerMacTests
        excludes:
          - "**/.DS_Store"
          - "Fixtures/**"
      - path: Sources/EDFViewerMac
        excludes:
          - "**/.DS_Store"
          - "App/EDFViewerMacApp.swift"
      - path: Tests/EDFViewerMacTests/Fixtures
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.goldenarc.edfviewer.tests
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_MODULE_NAME: EDFViewerMac
